name: Helpers

on:
 push:
    branches: [ master ]
    paths: 
      - 'Milvasoft.Iyzipay/**'

 pull_request:
    branches: [ master ]
    paths: 
      - 'Milvasoft.Iyzipay/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: Test
      #run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:   
       PROJECT_FILE_PATH: Milvasoft.Iyzipay/Milvasoft.Iyzipay.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
